<?php

namespace Drupal\hello_world\Plugin\Block;

use Drupal\Core\Block\BlockBase;
use Drupal\Core\Block\BlockPluginInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Plugin\ContainerFactoryPluginInterface;
use Drupal\hello_world\HelloWorldSalutation as HelloWorldSalutationService;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Hello World Salutation block.
 *
 * @Block(
 * id = "hello_world_salutation_block",
 * admin_label = @Translation("Hello world salutation"),
 * )
 */
class HelloWorldSalutationBlock extends BlockBase implements ContainerFactoryPluginInterface, BlockPluginInterface {


  /**
   * The salutation service.
   *
   * @var $salutation HelloWorldSalutationService
   */
  protected $salutation;

  public function __construct(array $configuration, $plugin_id, $plugin_definition, HelloWorldSalutationService $salutation)
  {
    $this->salutation = $salutation;
    parent::__construct($configuration, $plugin_id, $plugin_definition);
  }

  /**
   * {@inheritdoc}
   */
  public static function create(ContainerInterface $container, array
  $configuration, $plugin_id, $plugin_definition)
  {
    return new static(
      $configuration,
      $plugin_id,
      $plugin_definition,
      $container->get('hello_world.salutation')
    );
  }

  /**
   * Builds and returns the renderable array for this block plugin.
   *
   * If a block should not be rendered because it has no content, then this
   * method must also ensure to return no content: it must then only return an
   * empty array, or an empty array with #cache set (with cacheability metadata
   * indicating the circumstances for it being empty).
   *
   * @return array
   *   A renderable array representing the content of the block.
   *
   * @see \Drupal\block\BlockViewBuilder
   */
  public function build() {
    return [
      '#markup' => $this->salutation->getSalutation(),
    ];
  }

  public function defaultConfiguration()
  {
    return [
      'enabled' => 1,
    ];
  }

  public function blockForm($form, FormStateInterface $form_state)
  {
    $config = $this->defaultConfiguration();
    $form['enabled'] = [
      '#type' => 'checkbox',
      '#title' => t('Enabled'),
      '#description' => t('Check this block if you wanna enable this feature'),
      '#default_value' => $config['enabled'],
    ];
    return $form; // TODO: Change the autogenerated stub
  }

  public function blockSubmit($form, FormStateInterface $form_state)
  {
    parent::blockSubmit($form, $form_state); // TODO: Change the autogenerated stub
    $this->configuration['enabled'] = $form_state->getValue('enabled');
  }
}
