#!/usr/bin/env bash
## Run a BLT command inside the cli container.
##
## Usage: fin blt [command]

fin exec /var/www/vendor/bin/phpunit -c /var/www/docroot/phpunit.xml /var/www/docroot/modules/custom
